## Необходимо выполнить весь код, и написать комментарии к каждому блоку кода в блоках типа "MarkDown"

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

In [1]:
import this
print(int("313f0", 16) )

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
201712


## Типы данных

### int (целое число)

В этом блоке создается переменная `x` со значением 5, затем выводится ее значение и тип данных.
Функция `type()` показывает, что 5 является целым числом (int).

In [23]:
x = 5

print(x, '|', type(x))


5 | <class 'int'>


Демонстрация арифметических операций: сложение, умножение и целочисленное деление.
Оператор `//` выполняет деление без остатка, отбрасывая дробную часть.

In [24]:
a = 4 + 5
b = 4 * 5
c = 5 // 4

print(a, b, c)

9 20 1


Целочисленное деление через `//`

Здесь выполняется целочисленное деление 5 на 4 с помощью оператора //, который отбрасывает дробную часть. Результат равен 1, а унарный минус превращает его в -1. Этот оператор полезен когда нужен целый результат без остатка.

In [25]:
print( -(5 // 4) )

-1


Деление с остатком через `/`

В отличие от предыдущего примера, здесь используется обычное деление /, которое возвращает число с плавающей точкой. -5 делится на 4, получается -1.25. Оператор / всегда дает дробный результат, даже если числа делятся нацело.

In [21]:
print( -5 / 4 )

-1.25


Python без проблем обрабатывает очень большие целые числа. Здесь мы умножаем 5 на миллиард, затем еще на миллиард, потом на 10 в 9 степени и прибавляем 1. Результат выводится вместе с типом данных, который показывает что это целое число (int). В отличие от многих других языков, в Python нет ограничения на размер целых чисел.

In [30]:
x = 5 * 1000000000 * 1000000000 * 10**9 + 1
print(x, '|', type(x))

5000000000000000000000000001 | <class 'int'>


### float (число с плавающей точкой)

Переменной y присваивается дробное число 12.345. При выводе мы видим значение и тип данных - float (число с плавающей точкой). Такие числа используются для представления дробных значений и имеют ограниченную точность из-за способа хранения в памяти.

In [10]:
y = 12.345

print(y, type(y))

12.345 <class 'float'>


Здесь выполняются основные арифметические операции с дробными числами: сложение, умножение и деление. Результаты выводятся в консоль. Важно отметить, что при операциях с float могут возникать небольшие погрешности вычислений из-за двоичного представления чисел в компьютере.

In [31]:
a = 4.2 + 5.1
b = 4.2 * 5.1
c = 5.0 / 4.0

print(a, b, c)

9.3 21.419999999999998 1.25


Явное преобразование типов для деления

Здесь целые числа a и b явно преобразуются в float с помощью функции float(), после чего выполняется деление. Это гарантирует, что результат будет дробным числом, даже если исходные значения были целыми. Такой подход полезен когда точно нужен дробный результат.

In [32]:
a = 5
b = 4
print(float(a) / float(b))

1.25


Без явного преобразования типов

In [33]:
print(a / b)

1.25


### bool

Создаются две переменные логического типа: a=True (истина) и b=False (ложь). При выводе показываются их значения и тип данных. Bool часто используется в условиях и циклах для управления потоком выполнения программы.

In [34]:
a = True
b = False

print(a, '|', type(a))

print(b, '|', type(b))

True | <class 'bool'>
False | <class 'bool'>


Арифметические операции с bool

При сложении логических значений True и False они ведут себя как числа 1 и 0. True+False=1, True+True=2, False+False=0. Это показывает, что в числовых операциях bool автоматически преобразуются в целые числа.

In [35]:
print(a + b)
print(a + a)
print(b + b)

1
2
0


Функция int() явно преобразует логические значения в целые числа: True становится 1, а False становится 0. Это полезно когда нужно использовать логические значения в математических вычислениях.

In [36]:
print(int(a), int(b))

1 0


Демонстрация основных логических операторов: AND (и) возвращает True только если оба значения True, OR (или) возвращает True если хотя бы одно значение True, NOT (не) инвертирует значение. Символ '\n' добавляет пустую строку для лучшего чтения вывода.

In [37]:
print(True and False, '\n')

print(True or True, '\n')

print(not False, '\n')

False 

True 

True 



### None

Специальное значение None

Переменной z присваивается значение None, которое обозначает отсутствие значения или пустоту. При выводе видно, что None имеет собственный тип данных NoneType. Это полезно для инициализации переменных или обозначения отсутствия результата.

In [38]:
z = None
print(z, '|', type(z))

None | <class 'NoneType'>


Ошибка преобразования None в int

Попытка преобразовать None в целое число вызывает TypeError, так как None не является числом или строкой. None нельзя преобразовать в int, поскольку он представляет отсутствие значения, а не числовые данные.

In [42]:
int(z)

ValueError: invalid literal for int() with base 10: 'I am None!'

Проверка на None и изменение значения

С помощью условия if z is None: проверяется, содержит ли переменная z значение None. Если условие истинно, переменной присваивается новая строка. В конце выводится текущее значение z, которое теперь содержит текст вместо None.

In [43]:
if z is None:
    z = 'I am None!'
z

'I am None!'

Создание строк разными способами

Переменные x и y создаются с помощью двойных и одинарных кавычек - оба способа работают одинаково для создания строк. При выводе видно, что обе переменные имеют тип str. В Python нет разницы между строками в одинарных и двойных кавычках.

In [26]:
x = "abc"
y = 'xyz'
print(x, '|', type(x))
print(y, '|', type(y))

abc | <class 'str'>
xyz | <class 'str'>


Конкатенация строк

С помощью оператора + объединяются три строки: переменная a, пробел и переменная b. В результате получается полное имя "Федор Иванович". Конкатенация позволяет создавать новые строки путем соединения существующих.

In [44]:
a = 'Федор'
b = "Иванович"
s = a + " " + b
print(s)

Федор Иванович


Изменение регистра строк

Метод upper() преобразует все символы строки в верхний регистр, а lower() - в нижний. Эти методы полезны для нормализации текста перед сравнением или обработкой, не изменяя исходную строку.

In [45]:
print(a.upper())
print(a.lower())

ФЕДОР
федор


Определение длины строки

Функция len() возвращает количество символов в строке. Для строки 'Федор' результат равен 5, так как она состоит из 5 символов. Функция len() работает с любыми последовательностями в Python.

In [46]:
print(len(a))

5


Преобразование строк в bool

Функция bool() для непустой строки возвращает True, а для пустой строки (созданной сложением двух пустых строк) возвращает False. Это показывает, что пустые строки считаются ложными значениями в Python.

In [5]:
print(bool(a))
print(bool("" + ''))

True
False


Обращение к элементам строки

Демонстрация работы со строками как с последовательностями: обращение к отдельным символам по индексу и получение среза. Индексация начинается с 0, срез [0:3] возвращает первые три символа. Строки в Python поддерживают операции получения элементов по индексу.

In [47]:
print(a)
print(a[0])
print(a[1])
print(a[0:3])

Федор
Ф
е
Фед


Срезы с шагом

Срез [0:4:2] извлекает символы от 0 до 4 индекса с шагом 2. Для строки 'Федор' это позиции 0 ('Ф') и 2 ('д'), что дает результат 'Фд'. Третий параметр в срезе задает шаг выборки элементов.

In [48]:
print(a[0:4:2])

Фд


### Метод `split()`:

Разделение строки на список

Метод split(' ') разделяет строку по пробелам и возвращает список слов. Строка "Керемет Максим Максимович" преобразуется в список ['Керемет', 'Максим', 'Максимович']. split() полезен для обработки текстовых данных.

In [49]:
splitted_line = "Керемет Максим Максимович".split(' ')
print(splitted_line)

['Керемет', 'Максим', 'Максимович']


### tuple (кортеж)

Создание кортежа

Кортеж создается с помощью круглых скобок и может содержать элементы разных типов данных. В данном случае кортеж t содержит строки, целое и дробное число. Кортежи похожи на списки, но являются неизменяемыми.

In [58]:
t = ('a', 5, 12.345, 'a')
t

('a', 5, 12.345, 'a')

Попытка добавить элемент в кортеж вызывает ошибку AttributeError, так как кортежи являются неизменяемыми структурами данных. В отличие от списков, кортежи нельзя изменять после создания - нельзя добавлять, удалять или изменять элементы.

In [61]:
t.append(5)

AttributeError: 'tuple' object has no attribute 'append'

Функция dir() показывает все доступные методы и атрибуты объекта t. Для кортежа доступны только два метода: count() для подсчета элементов и index() для поиска индекса элемента, а также различные специальные методы, начинающиеся с двойного подчеркивания.

In [60]:
dir(t)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

Поиск индекса элемента в кортеже

Метод index() возвращает индекс первого вхождения элемента 'a' в кортеже t. В нашем случае 'a' находится на позиции 0. Если элемента нет в кортеже, метод вызовет ошибку ValueError.

In [63]:
t.index('a')

0

Обращение к элементу кортежа по индексу

Получение элемента кортежа с индексом 2, которым является число 12.345. Как и в строках и списках, индексация в кортежах начинается с 0. Кортежи поддерживают доступ к элементам по индексу, но не позволяют изменять их.

In [65]:
t[2]

12.345

Отображение содержимого кортежа

При вызове переменной t в интерактивном режиме Python автоматически выводит полное содержимое кортежа. Мы видим все элементы: ('a', 5, 12.345, 'a'). Кортеж сохраняет порядок элементов и позволяет дублирование значений.

In [66]:
t

('a', 5, 12.345, 'a')

Подсчет элементов в кортеже

Метод count() возвращает количество вхождений элемента 'a' в кортеже t. В нашем случае 'a' встречается 2 раза. Этот метод полезен для анализа частоты элементов в неизменяемых последовательностях.

In [67]:
t.count('a')

2

Конкатенация кортежей

Оператор + объединяет два кортежа t и m в один новый кортеж. Исходные кортежи не изменяются, создается новый кортеж, содержащий все элементы из t и m в порядке соединения.

In [69]:
m = (1, 2, 3)

t + m

('a', 5, 12.345, 'a', 1, 2, 3)

Ошибка вычитания кортежей

Попытка вычесть один кортеж из другого вызывает TypeError, так как операция вычитания не определена для кортежей. В Python кортежи поддерживают только конкатенацию и умножение, но не арифметические операции.

In [70]:
t - m

TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

Определение длины кортежа

Функция len() возвращает количество элементов в кортеже t. В данном случае кортеж содержит 4 элемента, поэтому результат равен 4. Функция len() работает для всех типов последовательностей в Python.



In [71]:
len(t)

4

#### Поменять переменные местами

Обмен значений переменных

Классический Python-трюк для обмена значений двух переменных без временной переменной. Выражение a, b = b, a меняет значения местами: a становится 100, b становится -5. Это работает благодаря распаковке кортежа.

In [73]:
a = -5
b = 100

a, b = b, a

print('a:', a, '\nb:', b)

a: 100 
b: -5


### Встроенные функции

Обращение к встроенному модулю

Переменная __builtin__ ссылается на модуль встроенных функций и типов Python. При обращении к ней показывается информация о модуле, содержащем все базовые функции типа print(), len(), int() и другие, доступные без импорта.

In [74]:
__builtin__

<module 'builtins' (built-in)>

In [9]:
dir(__builtin__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

Возведение в степень

Функция pow(2,2) выполняет возведение числа 2 в степень 2 и возвращает результат 4. Это эквивалентно выражению 2**2. Функция pow() может принимать третий аргумент для модульной арифметики.



In [75]:
pow(2,2)

4

### Структуры данных 

### list

Создание пустых списков

Два способа создания пустого списка: с помощью конструктора list() и через квадратные скобки []. Оба метода создают идентичные пустые списки, поэтому сравнение a == b возвращает True. Оба способа равнозначны и используются в разных ситуациях.

In [76]:
a = list()
b = []

print(a == b)

True


Создание списка с разными типами данных

Список my_list содержит элементы разных типов: строку, целое число, число с плавающей точкой и значение None. В Python списки могут хранить гетерогенные данные, что делает их очень гибкими для работы с различной информацией.

In [78]:
my_list = ['string', 100, 5.678, None]
my_list

['string', 100, 5.678, None]

Создание диапазона чисел

Функция range(1, 10, 2) создает объект диапазона от 1 до 10 с шагом 2. Вывод показывает, что это объект типа range, а не список. Range эффективно использует память, генерируя числа по требованию, а не храня их все сразу.

In [79]:
array = range(1, 10, 2)
print(array, '|', type(array))

range(1, 10, 2) | <class 'range'>


Преобразование range в список

Функция list() преобразует объект range в реальный список. Теперь array содержит [1, 3, 5, 7, 9] и имеет тип list. Это полезно, когда нужно работать с конкретными элементами диапазона или многократно обращаться к ним.

In [80]:
array = list(array)
print(array, '|', type(array))

[1, 3, 5, 7, 9] | <class 'list'>


Обращение к элементу списка по индексу

Получение элемента списка с индексом 1. В списке [1, 3, 5, 7, 9] элемент с индексом 1 равен 3. Индексация в Python начинается с 0, поэтому array[0] вернет 1, array[1] вернет 3 и так далее.

In [81]:
array[1]

3

Отрицательная индексация списка

Использование отрицательного индекса -2 для доступа ко второму элементу с конца списка. В списке [1, 3, 5, 7, 9] array[-1] вернет 9, array[-2] вернет 7. Отрицательные индексы удобны для доступа к элементам с конца последовательности.

In [82]:
array[-2]

7

Цикл for с функцией range

Цикл for последовательно перебирает числа от 0 до 4, сгенерированные range(5). На каждой итерации переменная i принимает следующее значение, которое выводится на экран. Range(5) создает последовательность 0,1,2,3,4.



In [83]:
for i in range(5):
    print(i)

0
1
2
3
4


**Полезно**:<br>
Перевернуть список можно так:

Разворот списка с помощью среза

Срез [::-1] создает перевернутую копию списка. Исходный список [1, 3, 5, 7, 9] превращается в [9, 7, 5, 3, 1]. Синтаксис [start:stop:step] с step=-1 позволяет легко разворачивать любые последовательности.

In [84]:
array = array[::-1]
array

[9, 7, 5, 3, 1]

**Полезно**:<br>
Срезы (`slice`'s) - это объекты языка Python, позволяющие получить какую-то часть итерируемого объекта.  
Пример:

Создание списка чисел от 0 до 9

Функция list(range(10)) создает список [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], содержащий все целые числа от 0 до 9 включительно. Range(10) генерирует числа от 0 до 9, а list() преобразует их в список.



In [85]:
foo = list(range(10))
foo

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Срез списка от начала до 5-го элемента

Синтаксис [:5] возвращает первые 5 элементов списка foo. Для списка [0,1,2,3,4,5,6,7,8,9] результат будет [0,1,2,3,4]. Срезы в Python не включают конечный индекс, поэтому элемент с индексом 5 не входит в результат.

In [86]:
foo[:5]

[0, 1, 2, 3, 4]

Срез списка от 5-го элемента до конца

Синтаксис [5:] возвращает все элементы списка начиная с индекса 5 до конца. Для списка [0,1,2,3,4,5,6,7,8,9] результат будет [5,6,7,8,9]. Если не указать конечный индекс, срез идет до последнего элемента.

In [87]:
foo[5:]

[5, 6, 7, 8, 9]

Срез списка от 2-го до 5-го элемента

Синтаксис [2:5] возвращает элементы с индексами 2, 3 и 4. Для списка [0,1,2,3,4,5,6,7,8,9] результат будет [2,3,4]. Срезы в Python включают начальный индекс, но не включают конечный (верхняя граница исключается).



In [88]:
foo[2:5]

[2, 3, 4]

Создание объекта slice

Функция slice(2, 5) создает объект среза, который можно использовать для извлечения части последовательности. Вывод показывает, что это объект типа slice. Объекты срезов удобно переиспользовать для одинаковых операций с разными списками.

In [89]:
slice_2_5 = slice(2, 5)
print(slice_2_5, '|', type(slice_2_5))

slice(2, 5, None) | <class 'slice'>


Применение объекта slice к списку

Использование созданного объекта slice_2_5 для извлечения элементов из списка foo. Результат [2,3,4] идентичен использованию синтаксиса [2:5]. Объекты срезов полезны когда нужно многократно применять один и тот же срез к разным последовательностям.

In [90]:
foo[slice_2_5]

[2, 3, 4]

Создание списка строк

Создается список str_array, содержащий буквы от 'a' до 'e'. Списки строк часто используются для обработки текстовых данных, хранения наборов значений и работы с последовательностями символов или слов.

In [94]:
str_array = ['a', 'b', 'c', 'd', 'e']
str_array

['a', 'b', 'c', 'd', 'e']

Объединение списка в строку

Метод join() объединяет элементы списка в одну строку с указанным разделителем. В первом случае разделитель - пробел ('a b c d e'), во втором - запятая ('a,b,c,d,e'). Join() эффективен для создания строк из списков.

In [95]:
print(' '.join(str_array))
print(','.join(str_array))

a b c d e
a,b,c,d,e


Конкатенация списков

Оператор + объединяет два списка a и b в один новый список [1,2,3,4,5,6]. Исходные списки остаются неизменными. Конкатенация создает новый объект списка, содержащий все элементы из обоих исходных списков.

In [96]:
a = [1, 2, 3]
b = [4, 5, 6]

print(a + b)

[1, 2, 3, 4, 5, 6]


### Методы класса list

Просмотр методов класса list

Функция dir(list) показывает все доступные методы и атрибуты для объектов типа список. Среди них основные методы для работы со списками: append(), sort(), pop(), remove(), extend() и другие, а также специальные методы с двойным подчеркиванием.

In [97]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

* `L.append(element)` - добавляет элемент `element` в список `L`

Добавление элемента в список

Метод append() добавляет новый элемент 'BANG!' в конец списка l. Исходный список [5,4,3,2,1] становится [5,4,3,2,1,'BANG!']. Append() изменяет список на месте и всегда добавляет элемент в конец.

In [98]:
l = [5, 4, 3, 2, 1]

l.append('BANG!')
l

[5, 4, 3, 2, 1, 'BANG!']

Сортировка списка без изменения оригинала

Функция sorted(l) возвращает новый отсортированный список [1,2,3,4,5], но исходный список l остается неизменным [5,4,3,2,1]. Sorted() не изменяет оригинальный список, в отличие от метода sort().

In [99]:
l = [5, 4, 3, 2, 1]
print(sorted(l), '|', l)

[1, 2, 3, 4, 5] | [5, 4, 3, 2, 1]


Проверка текущего состояния списка

Вывод содержимого списка l показывает, что он по-прежнему содержит [5,4,3,2], так как предыдущие операции не изменяли его напрямую. В интерактивном режиме Python автоматически выводит значение переменной при ее вызове.



In [100]:
l

[5, 4, 3, 2, 1]

Удаление и возврат последнего элемента

Метод pop() удаляет последний элемент списка (2) и возвращает его. После выполнения операции список l становится [5,4,3]. Pop() полезен для реализации структур данных типа стек (LIFO - последний пришел, первый ушел).

In [101]:
print(l.pop())
l

1


[5, 4, 3, 2]

Сравнение отсортированного и исходного списка

Функция sorted(l) возвращает новый отсортированный список [3,4,5], в то время как исходный список l остается неизменным [5,4,3]. Это демонстрирует разницу между sorted() (создает новую копию) и sort() (изменяет исходный список).

In [104]:
print(sorted(l), '|', l)

[2, 3, 4, 5] | [5, 4, 3, 2]


Создание функции для сравнения

Определяется функция cmp(string), которая принимает строку и возвращает ее длину. Эта функция будет использоваться как ключ для сортировки, позволяя сортировать элементы по их длине, а не по алфавитному порядку.

In [106]:
def cmp(string):
    return len(string)
cmp

<function __main__.cmp(string)>

Сортировка по длине строк

Функция sorted() с параметром key=cmp сортирует список имен по длине строк. Имена упорядочиваются от самого короткого ('Оля' - 3 символа) до самого длинного ('Анастасия' - 9 символов). Ключ cmp определяет критерий сортировки.

In [107]:
names = ['Александр', 'Василий', 'Анастасия', 'Соня', 'Френк', 'Оля']
sorted(names, key=cmp)

['Оля', 'Соня', 'Френк', 'Василий', 'Александр', 'Анастасия']

Сортировка с использованием lambda-функции

Lambda-функция lambda x: len(x) заменяет отдельную функцию cmp, возвращая длину каждого элемента. Результат сортировки идентичен предыдущему: имена упорядочены по длине от 'Оля' до 'Анастасия'. Lambda удобна для простых операций.

In [108]:
names = ['Александр', 'Василий', 'Анастасия', 'Соня', 'Френк', 'Оля']
sorted(names, key=lambda x: len(x))

['Оля', 'Соня', 'Френк', 'Василий', 'Александр', 'Анастасия']

Подсчет количества элементов в списке

Метод count(10) возвращает количество раз, которое число 10 встречается в списке l. В данном случае результат равен 2, так как список содержит две десятки. Count() полезен для анализа частоты элементов в последовательности.



In [109]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10]
l.count(10)

2

Поиск отсутствующего элемента

Метод count('python') возвращает 0, так как строка 'python' отсутствует в списке l. Count() всегда возвращает 0 для элементов, которых нет в списке, не вызывая ошибок. Это безопасный способ проверки наличия элементов.

In [111]:
l.count('python')

0

Определение длины списка

Функция len(l) возвращает количество элементов в списке l, которое равно 11. Len() работает для всех типов последовательностей (списки, кортежи, строки) и коллекций (словари, множества), возвращая число элементов.

In [112]:
len(l)

11

Ошибка поиска отсутствующего элемента

Метод index(11) пытается найти индекс элемента 11 в списке, но поскольку этого элемента нет, возникает ошибка ValueError. В отличие от count(), метод index() вызывает исключение при поиске отсутствующего элемента.

In [114]:
l.index(11)

ValueError: 11 is not in list

### Циклы - for и while

Итерация по списку в цикле for

Цикл for последовательно перебирает все элементы списка models. На каждой итерации переменная model принимает значение следующего элемента, которое выводится на печать. Это основной способ обработки элементов коллекций в Python.



In [115]:
models = ['decision tree', 'linear model', 'svm', 'ensemble']

for model in models:
    print(model)

decision tree
linear model
svm
ensemble


Цикл while с условием

Цикл while выполняется пока условие x > 50 истинно. На каждой итерации x уменьшается на 10 и выводится новое значение. Цикл продолжается до тех пор, пока x не станет равным 50, после чего условие становится ложным.

In [116]:
x = 100

while x > 50:
    x -= 10
    print(x)

90
80
70
60
50


Прикладной пример - убрать какие либо знаки, буквы и оставить цифры.

Фильтрация цифр из строки

Цикл перебирает каждый символ строки s. Метод isdigit() проверяет, является ли символ цифрой. Если да, символ добавляется к new_s. Pass используется для пропуска нецифровых символов. В результате извлекаются только цифры из исходной строки.



In [118]:
s = "Дата заказа:2018-10-14_аорыроарыов"
new_s= '' #создаем новую строку и в нее будем добавлять только те символы, которые удовлетворяют нашим условиям.

for i in s:
    if i.isdigit() == True: # метод .isdigit() проверяет является ли символ цифрой
        new_s += i # так в цикле добавляет символ и перезаписывается получившаяся строка
    else:
        pass # просто пропускаем символ

Результат фильтрации цифр

Переменная new_s содержит только цифры, извлеченные из исходной строки: '20181014'. Все нецифровые символы были отфильтрованы. Это полезно для очистки данных и извлечения числовой информации из текста.

In [119]:
new_s

'20181014'

Преобразование строки в дату

Библиотека pandas преобразует строку '20181014' в объект Timestamp, используя указанный формат "%Y%m%d" (год-месяц-день). Результат - 2018-10-14. Это полезно для работы с датами в анализе данных.

In [120]:
import pandas as pd
pd.to_datetime(new_s, format="%Y%m%d")

Timestamp('2018-10-14 00:00:00')

### enumerate, zip

Создание объекта zip

Функция zip() объединяет два списка first и second в итератор, который будет возвращать кортежи из соответствующих элементов: ('a','1'), ('b','2') и т.д. Zip() не создает список сразу, а генерирует элементы по мере необходимости.

In [121]:
first = 'a b c d e f g'.split(' ')
second = '1 2 3 4 5 6 7'.split(' ')

zip(first, second)

Преобразование zip в список

Функция list() преобразует объект zip в список кортежей, где каждый кортеж содержит соответствующие элементы из first и second: [('a','1'), ('b','2'), ...]. Это позволяет увидеть все пары элементов, созданные функцией zip().



In [123]:
list(zip(first, second))

[('a', '1'),
 ('b', '2'),
 ('c', '3'),
 ('d', '4'),
 ('e', '5'),
 ('f', '6'),
 ('g', '7')]

In [124]:
enum = enumerate(first)
list(enum)

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e'), (5, 'f'), (6, 'g')]

Нумерация элементов списка

Функция enumerate(first) создает итератор, который возвращает кортежи (индекс, элемент) для каждого элемента списка first. При преобразовании в список получаем [(0,'a'), (1,'b'), ...], что удобно для циклов с доступом к индексу.

In [138]:
enum = enumerate(first)
zip_style = zip(range(0, len(first)), first)

print(list(enum) == list(zip_style))

True


### list comprehensions

Создание списка через list comprehension

List comprehension [x for x in range(1, 6)] создает список [1,2,3,4,5]. Это компактная замена циклу for с append(), более читаемая и эффективная для создания списков на основе итераций.

In [139]:
a = [x for x in range(1, 6)]
a

[1, 2, 3, 4, 5]

Определение функции возведения в квадрат

Создается функция f(x), которая принимает число x и возвращает его квадрат (x²). Такие простые функции часто используются в комбинации с map(), filter() или как ключи для сортировки.



In [126]:
def f(x):
    return x ** 2

Сравнение двух способов создания списка квадратов

Оба list comprehension создают идентичные списки [1,4,9,16,25,36,49,64,81]. Первый использует функцию f(x), второй - прямое возведение в степень. Результат True подтверждает их эквивалентность.

In [127]:
b = [f(x) for x in range(1, 10)]
c = [x ** 2 for x in range(1, 10)]
print(b, '==', c)

[1, 4, 9, 16, 25, 36, 49, 64, 81] == [1, 4, 9, 16, 25, 36, 49, 64, 81]


Условные выражения в list comprehension

List comprehension с условием заменяет гласные буквы в строке 'apple' на самих себя, а согласные - на ''. Результат: ['a','','','','e']. Синтаксис x if condition else y позволяет фильтровать и преобразовывать элементы.

In [128]:
[x if x in 'aeiou' else '*' for x in 'apple']

['a', '*', '*', '*', 'e']

### functions

Функция с параметрами по умолчанию

Функция make_coffee принимает обязательный size и необязательный sugar_dose (по умолчанию 3). Проверяет количество сахара и возвращает сообщение. Параметры по умолчанию упрощают вызов функции.

In [129]:
def make_coffee(size, sugar_dose=3):
    if sugar_dose > 5:
        return 'Too much sugar! Be careful! :('
    else:
        return 'Done: cup of {0} ml size; amount of sugar = {1}'.format(size, sugar_dose)

Вызов функции с параметром по умолчанию

Функция вызывается только с размером 100, sugar_dose использует значение по умолчанию 3. Возвращается строка с информацией о размере и количестве сахара. Параметры по умолчанию позволяют упростить вызов функции.

In [131]:
make_coffee(100)

'Done: cup of 100 ml size; amount of sugar = 3'

Вызов функции с двумя параметрами

Функция принимает размер 200 и явное значение сахара 1. Поскольку 1 ≤ 5, возвращается сообщение о успешном приготовлении кофе с указанными параметрами. Явная передача параметров переопределяет значения по умолчанию.

In [132]:
make_coffee(200, 1)

'Done: cup of 200 ml size; amount of sugar = 1'

Проверка ограничения на сахар

При sugar_dose=6 срабатывает условие sugar_dose > 5, и функция возвращает предупреждение о превышении нормы сахара. Условные проверки в функциях позволяют контролировать допустимые значения параметров.

In [133]:
make_coffee(100, 6)

'Too much sugar! Be careful! :('

### set

Создание пустого множества

Функция set() создает пустое множество. Множества содержат только уникальные элементы и полезны для операций с неповторяющимися данными. Пустое множество отображается как set().

In [134]:
s = set()
s

set()

Просмотр методов множества

Функция dir(s) показывает все доступные методы для работы с множествами, включая add(), remove(), union(), intersection(), difference() и другие. Множества поддерживают математические операции над наборами.

In [135]:
dir(s)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

Добавление элементов в множество

Метод add() добавляет элементы в множество s. Множество может содержать элементы разных типов (числа, строки, None), но сохраняет только уникальные значения. Порядок элементов в множестве не гарантируется.



In [136]:
s.add(1)
s.add('a')
s.add(None)
s.add('bullet')
print(s)

{'bullet', 1, 'a', None}


Создание множеств из диапазонов

Два множества создаются из диапазонов чисел: s1 содержит 0-9, s2 содержит 5-14. Множества автоматически удаляют дубликаты и полезны для операций над наборами данных. Range преобразуется в set для работы с уникальными значениями.

In [137]:
s1 = set(range(0, 10))
s2 = set(range(5, 15))

Разность множеств

Метод difference() возвращает элементы, которые есть в первом множестве, но отсутствуют во втором. s1-s2 = {0,1,2,3,4}, s2-s1 = {10,11,12,13,14}. Разность показывает уникальные элементы каждого множества.

In [138]:
print(s1.difference(s2))
print()
print(s2.difference(s1))

{0, 1, 2, 3, 4}

{10, 11, 12, 13, 14}


Пересечение множеств

Метод intersection() возвращает общие элементы множеств s1 и s2. Результат {5,6,7,8,9} - числа, которые присутствуют в обоих множествах. Пересечение полезно для поиска совпадений в наборах данных.

In [153]:
s1.intersection(s2)

{5, 6, 7, 8, 9}

Объединение множеств

Метод union() возвращает все уникальные элементы из обоих множеств s1 и s2. Результат {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14} содержит все числа от 0 до 14 без повторений. Объединение наборы данных.

In [139]:
s1.union(s2)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}

Вывод содержимого множеств

Показывает текущее состояние множеств: s1 содержит {0,1,2,3,4,5,6,7,8,9}, s2 содержит {5,6,7,8,9,10,11,12,13,14}. Множества хранят элементы в произвольном порядке, но вывод обычно сортируется для удобства.

In [140]:
print('s1: ', s1, '\ns2: ', s2)

s1:  {0, 1, 2, 3, 4, 5, 6, 7, 8, 9} 
s2:  {5, 6, 7, 8, 9, 10, 11, 12, 13, 14}


### dict

Создание пустых словарей

Два способа создания пустого словаря: через {} и dict(). Оба метода создают идентичные объекты, поэтому сравнение возвращает True. Словари хранят данные в формате ключ-значение и очень эффективны для поиска.



In [141]:
d = {}
dd = dict()

print(d == dd, '|', type(d))

True | <class 'dict'>


Методы класса dict

Функция dir(dict) показывает все доступные методы словарей: keys(), values(), items(), get(), update(), pop() и другие. Словари предоставляют богатый API для работы с парными данными.

In [142]:
dir(dict)

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

Добавление элемента в словарь

Через квадратные скобки в словарь d добавляется ключ 'a' со значением 100. Словари позволяют быстро добавлять и получать значения по ключу. Ключи должны быть неизменяемыми типами данных.

In [143]:
d['a'] = 100
d

{'a': 100}

Создание словаря из списка кортежей

Функция dict() создает словарь из списка пар ключ-значение. Результат {1:1, 2:4} - ключи 1 и 2 с соответствующими значениями. Этот способ удобен для преобразования структурированных данных в словарь.



In [144]:
d = dict([(1, 1), (2, 4)])
d

{1: 1, 2: 4}

Создание словаря через именованные параметры

Функция dict() с именованными параметрами создает словарь {'short':'dict', 'long':'dictionary'}. Имена параметров становятся ключами, а их значения - значениями в словаре. Удобно для создания небольших словарей с строковыми ключами.

In [145]:
d = dict(short='dict', long='dictionary')
d

{'short': 'dict', 'long': 'dictionary'}

Методы доступа к данным словаря

keys() возвращает все ключи, values() - все значения, items() - пары ключ-значение. Эти методы полезны для итерации по словарю. Они возвращают специальные объекты просмотра, которые отражают изменения в словаре.

In [146]:
print(d.keys())
print(d.values())
print(d.items())

dict_keys(['short', 'long'])
dict_values(['dict', 'dictionary'])
dict_items([('short', 'dict'), ('long', 'dictionary')])


Безопасное получение значения по ключу

Метод get('short') возвращает значение для ключа 'short' - 'dict'. В отличие от d['short'], get() не вызывает ошибку при отсутствии ключа, а возвращает None (или значение по умолчанию).

In [148]:
d.get('short')

'dict'