# confluence_service.py

from atlassian import Confluence
from config import *


class ConfluenceService:

    def __init__(self):
        self.confluence = Confluence(
            url=CONFLUENCE_URL,
            username=CONFLUENCE_USER,
            password=CONFLUENCE_TOKEN,
            cloud=True
        )

    def create_release_page(self, version):

        html = f'''
        <h1>Release {version}</h1>
        <p>Automatic release generated by CI/CD orchestrator</p>
        '''

        self.confluence.create_page(
            space=CONFLUENCE_SPACE,
            title=f"Release {version}",
            body=html
        )
